route:
  receiver: 'discord-webhook'
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1m

receivers:
  - name: 'discord-webhook'
    discord_configs:
      - webhook_url: '${DISCORD_WEBHOOK_URL}'