apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer # أو NodePort لو شغال على Minikube محلياً
  selector:
    app: fastapi-rul
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000